import net.anvian.gradle.StripFabricLoomVersion

plugins {
    id 'multiloader-loader'
    id 'fabric-loom' version '1.6.12'
}

dependencies {
    registerTransform(StripFabricLoomVersion) {
        from.attribute(ArtifactTypeDefinition.ARTIFACT_TYPE_ATTRIBUTE, ArtifactTypeDefinition.JAR_TYPE)
        to.attribute(ArtifactTypeDefinition.ARTIFACT_TYPE_ATTRIBUTE, 'sanitized-fabric-jar')
    }

    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation 'com.google.code.findbugs:jsr305:3.0.1'
    modImplementation("net.anvian.anvianslib:anvianslib-fabric-${anvianslib_minecraft_version}:${anvianslib_version}")
}

loom {
    if (project(':common').file("src/main/resources/${mod_id}.accesswidener").exists()) {
        accessWidenerPath.set(project(':common').file("src/main/resources/${mod_id}.accesswidener"))
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('run')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('run')
        }
    }
}
