# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=2.0.1
group=net.anvian.gofish

# Common
minecraft_version=1.20.2
mod_name=Go Fish Rehooked
mod_author=Draylar
mod_id=gofish
license=MIT
credits=anvian
description=Go Fish Rehooked is a fishing expansion for Minecraft that turns fishing into a dimension-spanning progression system with biome-specific catches, weather and moon events, custom fishing rods, inventory-based lures, crates, recipes, and new treasure tables.
display_url=https://github.com/anviaan/GoFishRehooked/wiki
source_url=https://github.com/anviaan/GoFishRehooked
issue_tracker_url=https://github.com/anviaan/GoFishRehooked/issues
modrinth_url=https://modrinth.com/mod/nGvPJWKu
curseforge_url=https://www.curseforge.com/minecraft/mc-mods/go-fish
update_json_url=https://api.modrinth.com/updates/nGvPJWKu/forge_updates.json
minecraft_version_range=[1.20.2, 1.20.5)

# Fabric
fabric_version=0.91.0+1.20.2
fabric_loader_version=0.15.0

# Forge
forge_version=48.0.49
forge_loader_version_range=[48,)
forge_version_range=[48,)

# NeoForge
neoforge_version=20.2.86
neoforge_loader_version_range=[1,)

anvianslib_version=1.4.2

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
