# Project
version=2.0.1
group=net.anvian.gofish

# Common
java_version=21
minecraft_version=1.21.2
mod_name=Go Fish Rehooked
mod_author=Draylar
mod_id=gofish
license=MIT
credits=anvian
description=Go Fish Rehooked is a fishing expansion for Minecraft that turns fishing into a dimension-spanning progression system with biome-specific catches, weather and moon events, custom fishing rods, inventory-based lures, crates, recipes, and new treasure tables.
display_url=https://github.com/anviaan/GoFishRehooked/wiki
source_url=https://github.com/anviaan/GoFishRehooked
issue_tracker_url=https://github.com/anviaan/GoFishRehooked/issues
modrinth_url=https://modrinth.com/mod/nGvPJWKu
curseforge_url=https://www.curseforge.com/minecraft/mc-mods/go-fish
update_json_url=https://api.modrinth.com/updates/nGvPJWKu/forge_updates.json
minecraft_version_range=[1.21.2, 1.21.4)

# NeoForm / Parchment
neo_form_version=1.21.2-20241022.151510
parchment_minecraft=1.21
parchment_version=2024.11.10

# Fabric
fabric_version=0.106.1+1.21.2
fabric_loader_version=0.16.9

# NeoForge
neoforge_version=21.2.1-beta
neoforge_loader_version_range=[4,)

# Anvian's Lib
anvianslib_minecraft_version=1.21
anvianslib_version=1.4.2

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
