plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.add(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

dependencies {
    compileOnly 'org.spongepowered:mixin:0.8.5'
    compileOnly 'org.jetbrains:annotations:24.1.0'
    implementation 'com.google.code.findbugs:jsr305:3.0.1'
    implementation "net.anvian.anvianslib:anvianslib-common-${anvianslib_minecraft_version}:${anvianslib_version}"
    testImplementation 'junit:junit:4.13.2'
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}
