modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"
issueTrackerURL="https://github.com/anviaan/go-fish/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
logoFile = "${mod_id}.png"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
credits="${credits}"
authors = "${mod_author}"
description = '''${description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

[[dependencies.${mod_id}]] #optional
modId = "neoforge"
mandatory = true
versionRange = "${neoforge_loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "anvianslib"
mandatory = true
versionRange = "[${anvianslib_version},)"
ordering = "NONE"
side = "BOTH"